// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4_td6GVGnfzTdxnRelDIvJuvAUApEXo',
    appId: '1:71983413408:web:7eb32aa0667cdc41d031c5',
    messagingSenderId: '71983413408',
    projectId: 'workout-hwk',
    authDomain: 'workout-hwk.firebaseapp.com',
    storageBucket: 'workout-hwk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_Q9kHQH8k27mR7nOXKAGnGLSqzpVbaI',
    appId: '1:71983413408:android:66c587edf6615419d031c5',
    messagingSenderId: '71983413408',
    projectId: 'workout-hwk',
    storageBucket: 'workout-hwk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmRZ1h1dkZksoT0OqTa115cNG8HsVRHGU',
    appId: '1:71983413408:ios:90a75dac6e477b81d031c5',
    messagingSenderId: '71983413408',
    projectId: 'workout-hwk',
    storageBucket: 'workout-hwk.firebasestorage.app',
    iosBundleId: 'com.example.hwk3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmRZ1h1dkZksoT0OqTa115cNG8HsVRHGU',
    appId: '1:71983413408:ios:90a75dac6e477b81d031c5',
    messagingSenderId: '71983413408',
    projectId: 'workout-hwk',
    storageBucket: 'workout-hwk.firebasestorage.app',
    iosBundleId: 'com.example.hwk3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4_td6GVGnfzTdxnRelDIvJuvAUApEXo',
    appId: '1:71983413408:web:80ee63adf7414030d031c5',
    messagingSenderId: '71983413408',
    projectId: 'workout-hwk',
    authDomain: 'workout-hwk.firebaseapp.com',
    storageBucket: 'workout-hwk.firebasestorage.app',
  );
}
